services:
  postgres:
    image: postgres:17-alpine
    container_name: phoenix_bank_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - phoenix_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: phoenix_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@phoenix.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - phoenix_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  phoenix_pg_data:
  phoenix_pgadmin_data:
